name:                haskell
version:             0.1.0
github:              "davidainslie/scala-backwards"
license:             BSD3
author:              "David Ainslie"
maintainer:          "dainslie@gmail.com"
copyright:           "Copyright: (c) 2014 Backwards (David Ainslie)"

default-extensions:
  # Type Classes
  - MultiParamTypeClasses
  - FunctionalDependencies
  - TypeSynonymInstances
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - UndecidableInstances
  # Type System
  - GADTs
  - RankNTypes
  - PolyKinds
  - ScopedTypeVariables
  - DataKinds
  - KindSignatures
  - TypeApplications
  # Language Syntax
  - LambdaCase
  - TypeOperators
  # Monads
  - MonadComprehensions
  - ApplicativeDo
  # Deriving Functionality
  - DeriveFunctor
  - GeneralizedNewtypeDeriving
  # Other
  - TypeInType
  - ConstraintKinds

dependencies:
  - base >= 4.7 && < 5
  - transformers
  - transformers-base
  - logict
  - stm
  - mtl
  - unliftio
  - unliftio-core
  - containers
  - text

library:
  source-dirs: main/src/main/haskell/bookofmonads
#  ghc-options:
#  - -Wall

tests:
  haskell-test:
    main:                Spec.hs
    source-dirs:         main/src/test/haskell/bookofmonads
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - haskell
